/**
 * Built-in Assignments & Challenges — Ethiopian General Education Curriculum (MoE).
 * Content references official textbook units/strands used in Ethiopian secondary schools.
 */

import { CURRICULUM_FRAMEWORK, GRADES } from './subjects';

const framework = CURRICULUM_FRAMEWORK;

function assignment({
  curriculum_id,
  grade,
  subject,
  unit,
  type,
  difficulty,
  title,
  description,
  duration_minutes,
  xp_reward,
  status = 'available',
  accepted_by,
  content,
}) {
  return {
    id: curriculum_id,
    curriculum_id,
    builtin: true,
    framework,
    grade,
    subject,
    unit,
    type,
    difficulty,
    title,
    description,
    duration_minutes,
    xp_reward,
    category: subject,
    status,
    accepted_by,
    task_progress: {},
    content: {
      framework,
      grade,
      subject,
      unit,
      reference: content.reference,
      introduction: content.introduction,
      objectives: content.objectives,
      tasks: content.tasks,
      keyTerms: content.keyTerms || [],
    },
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  };
}

function challenge({
  curriculum_id,
  grade,
  subject,
  title,
  description,
  difficulty,
  duration_minutes,
  xp_reward,
  max_participants,
  status = 'recruiting',
  participant_emails = [],
  leader_email,
  content,
}) {
  return {
    id: curriculum_id,
    curriculum_id,
    builtin: true,
    framework,
    grade,
    subject,
    title,
    description,
    difficulty,
    status,
    duration_minutes,
    xp_reward,
    max_participants,
    participant_emails,
    leader_email,
    activity_progress: {},
    content: {
      framework,
      grade,
      subject,
      reference: content.reference,
      introduction: content.introduction,
      activities: content.activities,
      groupRules: content.groupRules || [],
    },
    created_date: new Date().toISOString(),
    updated_date: new Date().toISOString(),
  };
}

export function getBuiltinAssignments() {
  return [
    assignment({
      curriculum_id: 'eth-g9-hist-u2-d1',
      grade: 9,
      subject: 'history',
      unit: 'Unit 2: Resistance & Independence (19th–20th c.)',
      type: 'daily',
      difficulty: 'D',
      title: 'Adwa (1896) — causes & significance',
      description: 'Study the Battle of Adwa as a symbol of Ethiopian sovereignty in your Grade 9 History unit.',
      duration_minutes: 35,
      xp_reward: 70,
      content: {
        reference: 'Grade 9 History Student Textbook — Unit 2: Ethiopian Resistance to Colonialism',
        introduction:
          'The Ethiopian victory at Adwa (March 1896) is a core outcome in the MoE history strand on independence. Understand why Ethiopians united and what Adwa meant for Africa.',
        objectives: [
          'Explain Italy\'s colonial aims in the Horn of Africa after the Berlin Conference context.',
          'Describe key leaders (e.g. Emperor Menelik II, Empress Taytu, Ras Alula) and their roles.',
          'State three long-term effects of Adwa for Ethiopia and the Pan-African idea.',
        ],
        tasks: [
          { id: 't1', label: 'Read textbook section on Adwa (take 5 bullet notes)', type: 'read' },
          { id: 't2', label: 'Draw a simple timeline: 1889 treaty → 1895 crisis → 1896 battle', type: 'practice' },
          { id: 't3', label: 'Write 8 lines: Why is Adwa taught as a national symbol?', type: 'write' },
        ],
        keyTerms: ['Adwa', 'Menelik II', 'colonialism', 'sovereignty', 'Treaty of Wuchale'],
      },
    }),
    assignment({
      curriculum_id: 'eth-g9-geo-u1-d1',
      grade: 9,
      subject: 'geography',
      unit: 'Unit 1: Location & Physical Setting of Ethiopia',
      type: 'daily',
      difficulty: 'E',
      title: 'Ethiopia\'s location, relief & climate zones',
      description: 'Map skills and physical geography from the Grade 9 Geography textbook.',
      duration_minutes: 40,
      xp_reward: 55,
      content: {
        reference: 'Grade 9 Geography — Unit 1: Ethiopia and the Horn',
        introduction:
          'Ethiopia\'s position between 3°N–15°N and 33°E–48°E shapes climate, drainage, and human settlement patterns in the curriculum.',
        objectives: [
          'Locate Ethiopia relative to neighbours and major water bodies.',
          'Identify the Rift Valley, highlands, and lowlands on a sketch map.',
          'Link elevation to Köppen-style climate zones taught in class.',
        ],
        tasks: [
          { id: 't1', label: 'Label an outline map: capital, Blue Nile, Rift Valley, neighbours', type: 'practice' },
          { id: 't2', label: 'List 3 effects of highland climate on agriculture', type: 'write' },
          { id: 't3', label: 'Answer textbook check questions 1–4', type: 'practice' },
        ],
        keyTerms: ['Rift Valley', 'highlands', 'lowlands', 'rainfall', 'drainage'],
      },
    }),
    assignment({
      curriculum_id: 'eth-g9-math-u1-d1',
      grade: 9,
      subject: 'math',
      unit: 'Unit 1: Real Numbers & Operations',
      type: 'daily',
      difficulty: 'D',
      title: 'Real numbers on the number line',
      description: 'MoE Grade 9 Mathematics — rational, irrational, and operations.',
      duration_minutes: 30,
      xp_reward: 65,
      content: {
        reference: 'Grade 9 Mathematics — Unit 1: Real Numbers',
        introduction: 'Secondary mathematics in Ethiopia builds number sense before algebra strands in later units.',
        objectives: [
          'Classify numbers as natural, integer, rational, or irrational.',
          'Place √2 and fractions on a number line sketch.',
          'Apply order of operations on real-number expressions.',
        ],
        tasks: [
          { id: 't1', label: 'Complete exercises 1–8 (classification)', type: 'practice' },
          { id: 't2', label: 'Solve 5 order-of-operations problems from the textbook', type: 'practice' },
          { id: 't3', label: 'Write one real-life example using rational numbers', type: 'write' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g9-bio-u1-d1',
      grade: 9,
      subject: 'biology',
      unit: 'Unit 1: Introduction to Biology & Method',
      type: 'daily',
      difficulty: 'E',
      title: 'Scientific method & lab safety',
      description: 'Foundation unit before cell biology in the Ethiopian Grade 9 Biology course.',
      duration_minutes: 25,
      xp_reward: 50,
      content: {
        reference: 'Grade 9 Biology — Unit 1: Nature of Biology',
        introduction: 'Ethiopian biology emphasises observation, hypothesis, and safe practical work in school labs.',
        objectives: [
          'List steps of the scientific method used in your textbook.',
          'State lab safety rules from the MoE practical guide.',
          'Distinguish hypothesis, theory, and law in one paragraph each.',
        ],
        tasks: [
          { id: 't1', label: 'Copy the scientific method flowchart from the book', type: 'read' },
          { id: 't2', label: 'List 8 lab safety rules', type: 'write' },
          { id: 't3', label: 'Design a simple observation table for a seed germination demo', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g9-amh-u1-d1',
      grade: 9,
      subject: 'amharic',
      unit: 'Unit 1: ንባብ እና ጽሑፍ (Reading & Writing)',
      type: 'daily',
      difficulty: 'D',
      title: 'ንባብ ትምህርት — main idea & summary',
      description: 'Amharic mother-tongue strand: reading comprehension and short summary writing.',
      duration_minutes: 35,
      xp_reward: 60,
      content: {
        reference: 'Grade 9 Amharic — Unit 1: Reading Skills',
        introduction: 'Amharic curriculum develops ንባብ (reading) and ጽሑፍ (writing) for national examination competencies.',
        objectives: [
          'Identify the main idea (ዋና ሃሳብ) of a passage.',
          'Summarise a paragraph in 4–5 sentences in Amharic.',
          'Use new vocabulary from the unit word list correctly.',
        ],
        tasks: [
          { id: 't1', label: 'Read assigned passage twice aloud', type: 'read' },
          { id: 't2', label: 'Write a 5-sentence summary in Amharic', type: 'write' },
          { id: 't3', label: 'Define 6 vocabulary words from the unit list', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-math-u3-w1',
      grade: 10,
      subject: 'math',
      unit: 'Unit 3: Quadratic Equations & Functions',
      type: 'weekly',
      difficulty: 'C',
      title: 'Quadratic equations — factoring method',
      description: 'Weekly assignment aligned to Grade 10 Mathematics Unit 3.',
      duration_minutes: 55,
      xp_reward: 120,
      content: {
        reference: 'Grade 10 Mathematics — Unit 3: Quadratic Equations',
        introduction: 'Quadratic functions prepare students for EUEE/exit exam style problem solving.',
        objectives: [
          'Solve ax² + bx + c = 0 by factoring when possible.',
          'Sketch basic parabolas from vertex form introduced in class.',
          'Model one real problem (area or projectile) with a quadratic.',
        ],
        tasks: [
          { id: 't1', label: 'Complete textbook exercises 3.1 (1–12)', type: 'practice' },
          { id: 't2', label: 'Solve 5 past-paper style factoring problems', type: 'practice' },
          { id: 't3', label: 'Graph y = x² − 4x + 3 on graph paper', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-phy-u2-w1',
      grade: 10,
      subject: 'physics',
      unit: 'Unit 2: Motion in One Dimension',
      type: 'weekly',
      difficulty: 'C',
      title: 'Speed, velocity & acceleration problems',
      description: 'Kinematics unit from the Ethiopian Grade 10 Physics textbook.',
      duration_minutes: 60,
      xp_reward: 115,
      content: {
        reference: 'Grade 10 Physics — Unit 2: Motion',
        introduction: 'Physics uses SI units; Ethiopian texts use examples from transport and local engineering contexts.',
        objectives: [
          'Distinguish speed and velocity with direction.',
          'Use v = u + at and s = ut + ½at² for constant acceleration.',
          'Interpret distance–time and velocity–time graphs.',
        ],
        tasks: [
          { id: 't1', label: 'Solve numerical problems 1–6 (show units)', type: 'practice' },
          { id: 't2', label: 'Sketch graphs for one accelerated motion example', type: 'practice' },
          { id: 't3', label: 'Explain in 6 lines: negative acceleration in braking', type: 'write' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-eco-u1-w1',
      grade: 10,
      subject: 'economics',
      unit: 'Unit 1: Introduction to Economics & Ethiopian Economy',
      type: 'weekly',
      difficulty: 'D',
      title: 'Sectors of the Ethiopian economy',
      description: 'Economics strand on agriculture, industry, and services in Ethiopia.',
      duration_minutes: 45,
      xp_reward: 90,
      content: {
        reference: 'Grade 10 Economics — Unit 1: Economic Activities in Ethiopia',
        introduction: 'The curriculum links scarcity, choice, and Ethiopia\'s dominant agricultural sector.',
        objectives: [
          'Define primary, secondary, and tertiary sectors with Ethiopian examples.',
          'State the share of agriculture in employment (use textbook data).',
          'List three government goals for economic growth in the text.',
        ],
        tasks: [
          { id: 't1', label: 'Copy sector table from textbook with 2 examples each', type: 'read' },
          { id: 't2', label: 'Write 10 lines on role of smallholder farming', type: 'write' },
          { id: 't3', label: 'Answer end-of-unit questions 1–5', type: 'practice' },
        ],
        keyTerms: ['scarcity', 'agriculture', 'GDP', 'employment', 'industry'],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-chem-u2-d1',
      grade: 10,
      subject: 'chemistry',
      unit: 'Unit 2: Atomic Structure & Periodic Table',
      type: 'daily',
      difficulty: 'C',
      title: 'Atoms, isotopes & periodic trends',
      description: 'Grade 10 Chemistry — structure of matter before bonding units.',
      duration_minutes: 35,
      xp_reward: 85,
      content: {
        reference: 'Grade 10 Chemistry — Unit 2: Atomic Structure',
        introduction: 'Students learn subatomic particles and periodic table organisation per MoE science standards.',
        objectives: [
          'Describe proton, neutron, electron properties and location.',
          'Define isotope with Ethiopian textbook notation.',
          'Read atomic number and mass number from the periodic table provided in class.',
        ],
        tasks: [
          { id: 't1', label: 'Fill atomic structure worksheets (elements 1–20)', type: 'practice' },
          { id: 't2', label: 'Define isotope and give one medical example', type: 'write' },
          { id: 't3', label: 'Memorise first 20 element symbols', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-eng-u2-d1',
      grade: 10,
      subject: 'english',
      unit: 'Unit 2: Reading Comprehension & Summary',
      type: 'daily',
      difficulty: 'D',
      title: 'Reading passage — inference & vocabulary',
      description: 'English second-language strand preparing for national exam reading tasks.',
      duration_minutes: 40,
      xp_reward: 75,
      content: {
        reference: 'Grade 10 English — Unit 2: Reading Skills',
        introduction: 'Ethiopian English curriculum uses passages on development, environment, and citizenship themes.',
        objectives: [
          'Answer inference questions without copying full sentences.',
          'Summarise a passage in ≤ 80 words.',
          'Use context clues for 8 vocabulary items.',
        ],
        tasks: [
          { id: 't1', label: 'Read unit passage and annotate unknown words', type: 'read' },
          { id: 't2', label: 'Answer comprehension questions 1–7', type: 'practice' },
          { id: 't3', label: 'Write an 80-word summary', type: 'write' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g11-civ-u1-s1',
      grade: 11,
      subject: 'civics',
      unit: 'Unit 1: Constitution & Democratic Governance',
      type: 'story',
      difficulty: 'B',
      title: 'FDRE Constitution — rights & duties of citizens',
      description: 'Civics & Ethical Education core unit on constitutional citizenship.',
      duration_minutes: 90,
      xp_reward: 180,
      content: {
        reference: 'Grade 11 Civics & Ethical Education — Unit 1: Constitutional System',
        introduction: 'Students study the 1995 FDRE Constitution framework, institutions, and citizen responsibilities.',
        objectives: [
          'Name three branches of government and their roles.',
          'List five fundamental rights in the constitution chapter studied.',
          'Explain two civic duties (tax, defence, education, etc.) from the text.',
        ],
        tasks: [
          { id: 't1', label: 'Read Unit 1 and highlight rights vs duties', type: 'read' },
          { id: 't2', label: 'Create a comparison table: rights / duties / examples', type: 'practice' },
          { id: 't3', label: 'Write 1-page essay: responsible citizenship in school', type: 'write' },
          { id: 't4', label: 'Discuss in study group — prepare 3 oral points', type: 'discuss' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g11-hist-u3-s1',
      grade: 11,
      subject: 'history',
      unit: 'Unit 3: Ethiopia since 1974',
      type: 'story',
      difficulty: 'B',
      title: '1974–1991 period — causes & consequences',
      description: 'Contemporary Ethiopian history unit with structured source analysis.',
      duration_minutes: 100,
      xp_reward: 170,
      content: {
        reference: 'Grade 11 History — Unit 3: Modern Ethiopia',
        introduction: 'MoE history requires balanced understanding of political change and social impact since 1974.',
        objectives: [
          'Outline major events from 1974 to 1991 using textbook chronology.',
          'Identify economic and social policies discussed in class.',
          'Analyse one primary source excerpt from the student book.',
        ],
        tasks: [
          { id: 't1', label: 'Timeline with 10 dated events', type: 'practice' },
          { id: 't2', label: 'Source analysis worksheet (who, when, bias, message)', type: 'write' },
          { id: 't3', label: 'Answer essay prompt: social impact (250 words)', type: 'write' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g11-math-u4-s1',
      grade: 11,
      subject: 'math',
      unit: 'Unit 4: Trigonometry',
      type: 'story',
      difficulty: 'A',
      title: 'Trigonometric ratios & identities',
      description: 'Grade 11 Mathematics — trigonometry for pre-university exit exam.',
      duration_minutes: 120,
      xp_reward: 220,
      content: {
        reference: 'Grade 11 Mathematics — Unit 4: Trigonometry',
        introduction: 'Trigonometry links geometry and algebra; national exams include identity proofs and applications.',
        objectives: [
          'Define sin, cos, tan for acute angles in right triangles.',
          'Prove simple identities from the textbook list.',
          'Solve 5 application problems (heights/distances).',
        ],
        tasks: [
          { id: 't1', label: 'Complete exercises 4.2 and 4.3', type: 'practice' },
          { id: 't2', label: 'Prove identities #1–4 step by step', type: 'practice' },
          { id: 't3', label: 'Solve 3 height-of-building word problems', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g11-bio-u2-s1',
      grade: 11,
      subject: 'biology',
      unit: 'Unit 2: Human Biology — Nutrition & Digestion',
      type: 'story',
      difficulty: 'C',
      title: 'Digestive system & balanced diet',
      description: 'Human biology aligned to Ethiopian health and nutrition education messages.',
      duration_minutes: 75,
      xp_reward: 140,
      content: {
        reference: 'Grade 11 Biology — Unit 2: Human Nutrition',
        introduction: 'Links school science to national nutrition and food security topics in the curriculum.',
        objectives: [
          'Label digestive organs and state each organ\'s function.',
          'Define balanced diet using Ethiopian food examples.',
          'Explain malnutrition types mentioned in the textbook.',
        ],
        tasks: [
          { id: 't1', label: 'Draw and label digestive system diagram', type: 'practice' },
          { id: 't2', label: 'Plan a one-day balanced Ethiopian meal table', type: 'write' },
          { id: 't3', label: 'Answer unit review questions 1–10', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g12-eng-u4-s1',
      grade: 12,
      subject: 'english',
      unit: 'Unit 4: Essay Writing for Exit Exam',
      type: 'story',
      difficulty: 'A',
      title: 'Argumentative essay — structure & coherence',
      description: 'Grade 12 English exit-exam writing strand.',
      duration_minutes: 150,
      xp_reward: 250,
      content: {
        reference: 'Grade 12 English — Unit 4: Essay Writing',
        introduction: 'Exit exam essays require introduction, thesis, body paragraphs, and conclusion under time limits.',
        objectives: [
          'Write a thesis statement for a given prompt.',
          'Draft three body paragraphs with topic sentences.',
          'Use connectors from the MoE writing list correctly.',
        ],
        tasks: [
          { id: 't1', label: 'Outline essay on assigned prompt (education/technology)', type: 'write' },
          { id: 't2', label: 'Write full essay in 45 minutes timed', type: 'write' },
          { id: 't3', label: 'Peer-edit for grammar and coherence', type: 'discuss' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g12-phy-u5-s1',
      grade: 12,
      subject: 'physics',
      unit: 'Unit 5: Electricity & Magnetism',
      type: 'story',
      difficulty: 'A',
      title: 'Ohm\'s law & DC circuits',
      description: 'Grade 12 Physics — electricity for university entrance preparation.',
      duration_minutes: 110,
      xp_reward: 210,
      content: {
        reference: 'Grade 12 Physics — Unit 5: Current Electricity',
        introduction: 'Electricity units use circuit diagrams and calculations required on Ethiopian exit exams.',
        objectives: [
          'State Ohm\'s law and solve V = IR problems.',
          'Calculate equivalent resistance in series and parallel.',
          'Describe power P = VI and energy in kWh examples.',
        ],
        tasks: [
          { id: 't1', label: 'Solve circuit problems 1–10', type: 'practice' },
          { id: 't2', label: 'Draw series & parallel diagrams for 3 resistors', type: 'practice' },
          { id: 't3', label: 'Calculate monthly bill for sample kWh usage', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g12-eco-u3-s1',
      grade: 12,
      subject: 'economics',
      unit: 'Unit 3: Development & Plan in Ethiopia',
      type: 'story',
      difficulty: 'B',
      title: 'Development plans & sustainable growth',
      description: 'Economics unit on Ethiopian development policy and indicators.',
      duration_minutes: 95,
      xp_reward: 165,
      content: {
        reference: 'Grade 12 Economics — Unit 3: Economic Development',
        introduction: 'Students analyse GDP, HDI, poverty reduction, and plan documents referenced in MoE texts.',
        objectives: [
          'Define economic development vs growth.',
          'List indicators (GDP, HDI, employment) from the textbook.',
          'Describe one national plan goal and sector focus.',
        ],
        tasks: [
          { id: 't1', label: 'Read Unit 3 and note 8 key statistics', type: 'read' },
          { id: 't2', label: 'Compare two development indicators in a table', type: 'practice' },
          { id: 't3', label: '250-word essay: role of agriculture in development', type: 'write' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g9-ict-u1-d1',
      grade: 9,
      subject: 'ict',
      unit: 'Unit 1: Computer Systems & Digital Literacy',
      type: 'daily',
      difficulty: 'E',
      title: 'Hardware, software & safe internet use',
      description: 'MoE ICT curriculum — digital citizenship for Ethiopian students.',
      duration_minutes: 30,
      xp_reward: 50,
      content: {
        reference: 'Grade 9 ICT — Unit 1: Introduction to ICT',
        introduction: 'ICT introduces computer parts, operating systems, and responsible internet behaviour.',
        objectives: [
          'Name input, output, storage, and processing devices.',
          'Distinguish system vs application software.',
          'List 5 safe internet practices from the textbook.',
        ],
        tasks: [
          { id: 't1', label: 'Label computer diagram from textbook', type: 'practice' },
          { id: 't2', label: 'List 5 cyber-safety rules', type: 'write' },
          { id: 't3', label: 'Practice typing exercise 10 minutes', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-bio-u2-w1',
      grade: 10,
      subject: 'biology',
      unit: 'Unit 2: Cell Structure & Function',
      type: 'weekly',
      difficulty: 'C',
      title: 'Plant & animal cell organelles',
      description: 'Cell biology unit with microscope skills from Ethiopian lab manual.',
      duration_minutes: 50,
      xp_reward: 110,
      content: {
        reference: 'Grade 10 Biology — Unit 2: The Cell',
        introduction: 'Students compare plant and animal cells and relate organelles to function.',
        objectives: [
          'Draw and label plant and animal cells.',
          'Match organelles to functions (mitochondria, chloroplast, nucleus, etc.).',
          'Explain why cells are the basic unit of life.',
        ],
        tasks: [
          { id: 't1', label: 'Draw labelled diagrams (plant + animal)', type: 'practice' },
          { id: 't2', label: 'Complete organelle function matching sheet', type: 'practice' },
          { id: 't3', label: 'Answer 5 short-answer questions from unit review', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g10-hist-u2-w1',
      grade: 10,
      subject: 'history',
      unit: 'Unit 2: Africa & Colonialism',
      type: 'weekly',
      difficulty: 'C',
      title: 'Colonialism in Africa — Ethiopian context',
      description: 'World history unit situating Ethiopia alongside African colonial experiences.',
      duration_minutes: 55,
      xp_reward: 105,
      content: {
        reference: 'Grade 10 History — Unit 2: Colonial Rule in Africa',
        introduction: 'Curriculum compares partition of Africa with Ethiopia\'s independence narrative.',
        objectives: [
          'Explain the Berlin Conference in 2 paragraphs.',
          'Give two examples of colonial economies in Africa.',
          'Contrast independent Ethiopia with colonised neighbours.',
        ],
        tasks: [
          { id: 't1', label: 'Map colouring: colonising powers in Africa 1914', type: 'practice' },
          { id: 't2', label: 'Write comparison paragraph: Ethiopia vs one colony', type: 'write' },
          { id: 't3', label: 'Answer textbook questions 1–6', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g11-geo-u2-s1',
      grade: 11,
      subject: 'geography',
      unit: 'Unit 2: Population & Development in Ethiopia',
      type: 'story',
      difficulty: 'B',
      title: 'Population growth, migration & resources',
      description: 'Grade 11 Geography — demography and sustainable development.',
      duration_minutes: 85,
      xp_reward: 155,
      content: {
        reference: 'Grade 11 Geography — Unit 2: Population',
        introduction: 'Uses Ethiopian census concepts, age structure, and rural–urban migration from MoE materials.',
        objectives: [
          'Interpret population pyramids from textbook examples.',
          'Explain push/pull factors for rural–urban migration in Ethiopia.',
          'Link population pressure to resource use and planning.',
        ],
        tasks: [
          { id: 't1', label: 'Draw and annotate a population pyramid', type: 'practice' },
          { id: 't2', label: 'Case study: Addis Ababa migration (10 lines)', type: 'write' },
          { id: 't3', label: 'Answer data-response questions from unit', type: 'practice' },
        ],
      },
    }),
    assignment({
      curriculum_id: 'eth-g12-chem-u4-s1',
      grade: 12,
      subject: 'chemistry',
      unit: 'Unit 4: Organic Chemistry Introduction',
      type: 'story',
      difficulty: 'A',
      title: 'Hydrocarbons & functional groups',
      description: 'Grade 12 Chemistry — organic basics for exit exam.',
      duration_minutes: 100,
      xp_reward: 200,
      content: {
        reference: 'Grade 12 Chemistry — Unit 4: Organic Chemistry',
        introduction: 'Introduces alkanes, alkenes, and functional groups with IUPAC naming practice.',
        objectives: [
          'Name simple alkanes up to C6.',
          'Distinguish saturated vs unsaturated hydrocarbons.',
          'Identify alcohol and carboxylic acid groups in structures.',
        ],
        tasks: [
          { id: 't1', label: 'Name 10 structures from practice sheet', type: 'practice' },
          { id: 't2', label: 'Complete reactions worksheet (combustion, addition)', type: 'practice' },
          { id: 't3', label: 'Summary table of functional groups', type: 'write' },
        ],
      },
    }),
  ];
}

export function getBuiltinChallenges() {
  return [
    challenge({
      curriculum_id: 'eth-ch-g9-math-prep',
      grade: 9,
      subject: 'math',
      title: 'Grade 9 Math: Real Numbers Study Room',
      description: 'Group practice for Unit 1 exercises before the class test.',
      difficulty: 'C',
      duration_minutes: 45,
      xp_reward: 320,
      max_participants: 6,
      content: {
        reference: 'Grade 9 Mathematics — Unit 1',
        introduction: 'Work together on MoE textbook exercises; compare methods for fractions and radicals.',
        activities: [
          { id: 'a1', label: 'Each member solves 3 classification problems' },
          { id: 'a2', label: 'Group checks answers on the board/screen' },
          { id: 'a3', label: 'Teach one difficult problem to the group' },
        ],
        groupRules: ['Stay on curriculum topic only', '25-minute focused block, then 5-minute break'],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g9-hist-adwa',
      grade: 9,
      subject: 'history',
      title: 'Adwa History Challenge',
      description: 'Collaborative timeline and quiz on Unit 2 independence themes.',
      difficulty: 'D',
      duration_minutes: 50,
      xp_reward: 280,
      max_participants: 8,
      content: {
        reference: 'Grade 9 History — Unit 2',
        introduction: 'Build a shared timeline and oral presentation of Adwa\'s significance.',
        activities: [
          { id: 'a1', label: 'Create shared timeline (1880s–1900)' },
          { id: 'a2', label: 'Each student presents one leader\'s role (2 min)' },
          { id: 'a3', label: 'Group writes 5 exam-style questions with answers' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g10-phy-motion',
      grade: 10,
      subject: 'physics',
      title: 'Motion Problems Sprint',
      description: 'Pair solving of kinematics from Grade 10 Physics Unit 2.',
      difficulty: 'B',
      duration_minutes: 60,
      xp_reward: 450,
      max_participants: 5,
      content: {
        reference: 'Grade 10 Physics — Unit 2',
        introduction: 'Rotate through textbook numerical problems; show full working with SI units.',
        activities: [
          { id: 'a1', label: 'Solve problems 1–8 in pairs' },
          { id: 'a2', label: 'Peer-mark using answer key' },
          { id: 'a3', label: 'Redo missed problems individually' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g10-eco-sectors',
      grade: 10,
      subject: 'economics',
      title: 'Ethiopian Economy Sectors Blitz',
      description: 'Map agriculture, industry & services with real Ethiopian examples.',
      difficulty: 'C',
      duration_minutes: 40,
      xp_reward: 300,
      max_participants: 6,
      content: {
        reference: 'Grade 10 Economics — Unit 1',
        introduction: 'Poster-style activity: each group documents one sector with statistics from the textbook.',
        activities: [
          { id: 'a1', label: 'Research sector data from textbook tables' },
          { id: 'a2', label: 'Prepare 1-slide or poster summary' },
          { id: 'a3', label: 'Present and ask 2 questions to other groups' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g11-civ-constitution',
      grade: 11,
      subject: 'civics',
      title: 'Constitution & Citizenship Forum',
      description: 'Structured debate on rights and duties from Civics Unit 1.',
      difficulty: 'B',
      duration_minutes: 75,
      xp_reward: 480,
      max_participants: 8,
      content: {
        reference: 'Grade 11 Civics — Unit 1',
        introduction: 'Respectful debate using only textbook constitutional articles studied in class.',
        activities: [
          { id: 'a1', label: 'Assign pro/con on a school citizenship topic' },
          { id: 'a2', label: '10-minute preparation with textbook citations' },
          { id: 'a3', label: 'Round-table: 3 rights + 3 duties everyone must know' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g11-math-trig',
      grade: 11,
      subject: 'math',
      title: 'Trigonometry Identity Workshop',
      description: 'Group proof practice for Grade 11 Unit 4 identities.',
      difficulty: 'A',
      duration_minutes: 90,
      xp_reward: 550,
      max_participants: 4,
      content: {
        reference: 'Grade 11 Mathematics — Unit 4',
        introduction: 'Focus on identity proofs commonly set in Ethiopian national exams.',
        activities: [
          { id: 'a1', label: 'Each member proves one assigned identity' },
          { id: 'a2', label: 'Group verifies steps on whiteboard' },
          { id: 'a3', label: 'Solve 5 application problems together' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g12-eng-essay',
      grade: 12,
      subject: 'english',
      title: 'Exit Exam Essay Marathon',
      description: 'Timed argumentative essays with peer feedback (English Unit 4).',
      difficulty: 'A',
      duration_minutes: 80,
      xp_reward: 520,
      max_participants: 6,
      content: {
        reference: 'Grade 12 English — Unit 4',
        introduction: 'Simulate exam conditions: 45-minute essay + 15-minute peer review.',
        activities: [
          { id: 'a1', label: 'Write essay on MoE-style prompt (timed)' },
          { id: 'a2', label: 'Exchange papers — check thesis & paragraphs' },
          { id: 'a3', label: 'List 5 grammar fixes per partner' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g12-phy-circuits',
      grade: 12,
      subject: 'physics',
      title: 'DC Circuit Challenge Lab',
      description: 'Collaborative circuit calculations for Grade 12 Physics Unit 5.',
      difficulty: 'A',
      duration_minutes: 70,
      xp_reward: 500,
      max_participants: 5,
      content: {
        reference: 'Grade 12 Physics — Unit 5',
        introduction: 'If lab equipment is available, verify Ohm\'s law; otherwise use simulation diagrams from textbook.',
        activities: [
          { id: 'a1', label: 'Calculate series & parallel resistances' },
          { id: 'a2', label: 'Measure or simulate V and I for one circuit' },
          { id: 'a3', label: 'Submit group solution set (problems 1–6)' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g10-bio-cells',
      grade: 10,
      subject: 'biology',
      title: 'Cell Biology Drawing Challenge',
      description: 'Accurate cell diagrams per Grade 10 Biology Unit 2 lab standards.',
      difficulty: 'C',
      duration_minutes: 45,
      xp_reward: 310,
      max_participants: 6,
      content: {
        reference: 'Grade 10 Biology — Unit 2',
        introduction: 'Compare plant vs animal cell drawings; label all organelles from MoE list.',
        activities: [
          { id: 'a1', label: 'Individual labelled diagrams' },
          { id: 'a2', label: 'Group creates combined revision poster' },
          { id: 'a3', label: 'Quiz each other on organelle functions' },
        ],
      },
    }),
    challenge({
      curriculum_id: 'eth-ch-g12-neae-review',
      grade: 12,
      subject: 'math',
      title: 'Grade 12 Exit Exam Math Review',
      description: 'Mixed review: algebra, trigonometry & calculus preview items from MoE bank.',
      difficulty: 'S',
      duration_minutes: 120,
      xp_reward: 650,
      max_participants: 5,
      content: {
        reference: 'Grade 12 Mathematics — Exit Exam Preparation',
        introduction: 'Rotate through past national exam style items under teacher/textbook guidance.',
        activities: [
          { id: 'a1', label: '20-minute algebra problem set' },
          { id: 'a2', label: '20-minute trigonometry set' },
          { id: 'a3', label: 'Group marks answers using official-style memo' },
        ],
      },
    }),
  ];
}

export function getGradeFilter() {
  try {
    const g = parseInt(localStorage.getItem('studified_grade'), 10);
    if (GRADES.includes(g)) return g;
  } catch {
    /* ignore */
  }
  return 10;
}

export function setGradeFilter(grade) {
  localStorage.setItem('studified_grade', String(grade));
}
